#include "config.h"

#define RSTOOLS_XSTR(x) #x
#define RSTOOLS_STR(x) RSTOOLS_XSTR(x)
#define RSTOOLS_VERSION_HASH_STRING RSTOOLS_VERSION_HASH
#define RSTOOLS_VERSION_DATE_STRING RSTOOLS_VERSION_DATE
#define RSTOOLS_VERSION VERSION " (" RSTOOLS_VERSION_HASH_STRING " - " RSTOOLS_VERSION_DATE_STRING ")"
#define RSTOOLS_VERSION_LABEL "RSTools " RSTOOLS_VERSION
